import {
  runtimeContract,
  selectionSchema,
  validateProjectConnection,
} from "./vendor/connectors/connection-contract.mjs";
import { wrapper, wrapperSha256 } from "../plugin/connector-assets.mjs";
const text = { type: "string", minLength: 1 };
const object = (properties) => ({
  type: "object",
  properties,
  required: Object.keys(properties),
  additionalProperties: false,
});
const executionSchema = object({
  mode: { enum: ["databricks"], type: "string" },
  existingClusterId: text,
  bundleDirectory: text,
  notebookPath: text,
  pythonExecutable: text,
  azure: object({
    storageAccount: text,
    container: text,
    prefix: text,
    tenantId: text,
    clientId: text,
    clientSecretEnv: text,
  }),
  secrets: {
    type: "object",
    additionalProperties: object({ scope: text, key: text }),
  },
});
export const connectorRuntimes = {
  [runtimeContract]: {
    selectionSchema,
    executionSchema,
    executionPlatforms: ["databricks"],
    prepareCommand: "connection prepare",
    contractsCommand: "connector contracts",
  },
};
export const connectionDefinition = {
  name: "connection prepare",
  description:
    "Prepare a driver-side connector job using locked source assets; no workspace calls.",
  inputSchema: { type: "object", additionalProperties: true },
};
const check = (value, message) => {
  if (!value) throw Error(message);
};
export function prepare(request) {
  const { runtimeAssets, ...input } = request;
  check(
    runtimeAssets && input.runtimeAssetSha256,
    "Install a source package containing locked runtime assets",
  );
  const selection = validateProjectConnection(input, {
    ...connectorRuntimes[runtimeContract],
    settingsSchema: JSON.parse(runtimeAssets["settings.schema.json"]),
  });
  check(
    runtimeAssets && input.runtimeAssetSha256,
    "Install a source package containing locked runtime assets",
  );
  const e = input.execution,
    a = e.azure;
  check(
    /^[A-Za-z0-9-]+$/.test(e.existingClusterId),
    "Invalid existing cluster",
  );
  check(
    [e.bundleDirectory, e.notebookPath].every(
      (p) =>
        /^\/Workspace\/[A-Za-z0-9_./@-]+$/.test(p) &&
        !p.split("/").includes(".."),
    ),
    "Use absolute Workspace paths",
  );
  check(
    /^\/(?:[A-Za-z0-9_.-]+\/)*python(?:3(?:\.12)?)?$/.test(
      e.pythonExecutable,
    ) && !e.pythonExecutable.split("/").includes(".."),
    "Select a preinstalled Python executable",
  );
  check(
    /^[a-z0-9]{3,24}$/.test(a.storageAccount) &&
      /^[a-z0-9][a-z0-9-]{1,61}[a-z0-9]$/.test(a.container),
    "Invalid Blob destination",
  );
  check(
    a.prefix
      .split("/")
      .every((p) => /^[A-Za-z0-9][A-Za-z0-9_-]{0,100}$/.test(p)),
    "Invalid Blob prefix",
  );
  check(
    [a.tenantId, a.clientId].every((v) => /^[a-fA-F0-9-]{36}$/.test(v)),
    "Invalid storage identity",
  );
  const needed = new Set([a.clientSecretEnv]);
  function secrets(value) {
    if (!value || typeof value !== "object") return;
    if (value.$secret) {
      check(
        Object.keys(value.$secret).join(",") === "env",
        "Databricks uses secret-scope environment references",
      );
      needed.add(value.$secret.env);
    } else Object.values(value).forEach(secrets);
  }
  secrets(input.settings);
  check(
    [...needed].every(
      (n) => /^INGESTRON_[A-Z0-9_]+$/.test(n) && Object.hasOwn(e.secrets, n),
    ) && Object.keys(e.secrets).every((n) => needed.has(n)),
    "Map exactly the required secret environment names",
  );
  check(
    Object.values(e.secrets).every((v) =>
      [v.scope, v.key].every((s) => /^[A-Za-z0-9_@.-]{1,128}$/.test(s)),
    ),
    "Invalid scope/key",
  );
  const artifacts = { ...runtimeAssets };
  const lock = JSON.parse(artifacts["runtime.lock.json"]);
  check(
    lock.connector === input.connector.split(":")[1],
    "Runtime connector mismatch",
  );
  check(!artifacts["databricks_launch.py"], "Runtime wrapper collision");
  artifacts["databricks_launch.py"] = wrapper;
  lock.files["databricks_launch.py"] = wrapperSha256;
  artifacts["runtime.lock.json"] = JSON.stringify(lock, null, 2);
  artifacts["connector.json"] = JSON.stringify(
    {
      apiVersion: "ingestron.singer/v1",
      mode: "customer-operated",
      connector: lock.connector,
      sourceId: input.sourceId,
      tenantId: input.tenantId,
      configEnv: "INGESTRON_TAP_CONFIG",
      timeoutSeconds: input.timeoutSeconds,
      reviewFile: "review.json",
      sourceSettings: input.settings,
      projectLock: input,
      azure: a,
    },
    null,
    2,
  );
  artifacts["project-connection.lock.json"] = JSON.stringify(input, null, 2);
  artifacts["selection.json"] = JSON.stringify(selection, null, 2);
  artifacts["connector-notebook.py"] =
    `# Databricks notebook source\n# Generated by Ingestron. Upload the reviewed bundle before running.\nimport sys\nsys.path.insert(0, ${JSON.stringify(e.bundleDirectory)})\nfrom databricks_launch import launch\ndbutils.widgets.text("run_id", "")\nresult = launch(dbutils, ${JSON.stringify(e.bundleDirectory)}, ${JSON.stringify(e.pythonExecutable)}, dbutils.widgets.get("run_id"))\nprint(result)\n`;
  artifacts["job.json"] = JSON.stringify(
    {
      name: `ingestron-${input.sourceId}-${input.tenantId}`,
      max_concurrent_runs: 1,
      parameters: [{ name: "run_id", default: "" }],
      tasks: [
        {
          task_key: "ingest",
          existing_cluster_id: e.existingClusterId,
          timeout_seconds: 2 * input.timeoutSeconds + 300,
          max_retries: 2,
          min_retry_interval_millis: 30000,
          retry_on_timeout: true,
          notebook_task: {
            notebook_path: e.notebookPath,
            source: "WORKSPACE",
            base_parameters: { run_id: "{{job.parameters.run_id}}" },
          },
        },
      ],
    },
    null,
    2,
  );
  return {
    apiVersion: "ingestron.artifact-proposal/v1",
    applied: false,
    artifacts,
    execution: "databricks-driver-preview",
    review: [
      "Run on existing customer compute with preinstalled hash-locked Python 3.12 dependencies.",
      "Upload connector-notebook.py to notebookPath and all reviewed runtime files to bundleDirectory.",
      "Supply a stable business run_id. Retries reuse it; a new ID starts a new full snapshot.",
      "Single-driver extraction, not distributed Spark. Blob commit manifests identify complete snapshots.",
      "Offline native assets only; workspace execution and permissions are not verified.",
    ],
  };
}
